from milcapy import SystemModel
import pandas as pd
import numpy as np
theta = np.pi*45/180
model = SystemModel()
model.add_material("concreto", 2.1e6, 0.3, 10)
model.add_circular_section("CIRD=0.5", "concreto", 0.5)
# model.set_property_modifiers("CIRD=0.5", 1.2, 1, 1.4, 1.5)
model.add_node(1, 0.0, 0.0)
model.add_node(2, 0.0, 3.5)
model.add_node(3, 3.5, 3.5)
model.add_node(4, 7.0, 3.5)
model.add_node(5, 7.0, 0.0)
model.add_node(6, 3.5, 0.0)
model.add_elastic_timoshenko_beam(1, 1, 2, "CIRD=0.5")
model.add_elastic_timoshenko_beam(2, 2, 3, "CIRD=0.5")
model.add_elastic_timoshenko_beam(3, 3, 4, "CIRD=0.5")
model.add_elastic_timoshenko_beam(4, 4, 5, "CIRD=0.5")
model.add_elastic_timoshenko_beam(5, 2, 6, "CIRD=0.5")
model.add_restraint(1, *(True, True, True))
model.add_restraint(5, *(True, True, True))
model.add_restraint(6, *(False, True, False))
model.add_local_axis_for_node(6, theta)
# model.add_elastic_support(6, 10, 0, 0, "GLOBAL")
# model.add_local_axis_for_node(1, theta)
model.add_load_pattern("dead")
model.add_point_load(2, "dead", 1e5, -1e5, 0)
model.solve()
# kg = model.get_global_stiffness_matrix()
# df_kg = pd.DataFrame(kg)
# df_kg.to_excel("kg.xlsx")
# fg = model.get_global_load_vector("dead")
# df_fg = pd.DataFrame(fg)
# df_fg.to_excel("fg.xlsx")
model.show()